Murtino/Controllers/GlasacController.cs
using CsvHelper;
using Murtino.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Murtino.Controllers
{
    public class GlasacController : Controller
    {
        public ActionResult Index(long? id)
        {
            UserModel user = Constants.CurrentUser;
            ViewBag.Opcine = DB.Opcine(user.StrankaID.Value);
            if (id.HasValue) return View(DB.Glasac(id.Value, user.StrankaID.Value));
            return View(new GlasacModel());
        }

        [HttpPost]
        public ActionResult Upsert(GlasacModel model)
        {
            UserModel user = Constants.CurrentUser;

            if (!ModelState.IsValid)
            {
                ViewBag.Opcine = DB.Opcine(user.StrankaID.Value);
                return View("Index", model);
            }

            if (DB.Glasac(model, user.StrankaID.Value))
            {
                if (Request.IsAjaxRequest()) return Json(new { success = true });
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Opcine = DB.Opcine(user.StrankaID.Value);
                ModelState.AddModelError("", "Dodavanje glasača nije uspjelo.");
                return View("Index", model);
            }
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            UserModel user = Constants.CurrentUser;
            return Json(new { success = DB.DeleteGlasac(id, user.StrankaID.Value), redirect = Url.Action("Index", "Home") });
        }

        [HttpGet]
        public ActionResult Import()
        {
            return PartialView("_ImportGlasaci", Session[Session.SessionID] as StrankaViewModel);
        }

        [HttpPost]
        public ActionResult Import(long opcinaId, long birackoMjestoId, string delimiter)
        {
            HttpFileCollectionBase files = Request.Files;
            if (files != null && files.Count > 0)
            {
                try
                {
                    var file = files[0];
                    if (file.ContentLength == 0) return Content("File empty.");

                    using (var reader = new StreamReader(file.InputStream, System.Text.Encoding.UTF8))
                    {
                        CsvReader csv = new CsvReader(reader);
                        csv.Configuration.Delimiter = String.IsNullOrWhiteSpace(delimiter) ? ";" : delimiter;
                        csv.Configuration.Encoding = System.Text.Encoding.UTF8;
                        csv.Configuration.RegisterClassMap<GlasacClassMap>();
                        var records = csv.GetRecords<GlasacModel>().ToList();
                        UserModel user = Constants.CurrentUser;
                        records.ForEach(o =>
                        {
                            o.Ime = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(o.Ime.ToLower());
                            o.ImeOca = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(o.ImeOca.ToLower());
                            o.Prezime = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(o.Prezime.ToLower());
                            o.OpcinaID = opcinaId;
                            o.BirackoMjestoID = birackoMjestoId;
                        });
                        DB.ImportGlasaci(records, user.StrankaID.Value, opcinaId, birackoMjestoId);
                        return new EmptyResult();
                    }
                }
                catch (Exception ex)
                {
                    return Content(ex.Message);
                }
                
            }
            return Content("File upload failed.");
        }
    }
}

Murtino/Controllers/PosmatracController.cs
using CsvHelper;
using Murtino.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Murtino.Controllers
{
    public class PosmatracController : Controller
    {
        public ActionResult Index(long? id)
        {
            UserModel user = Constants.CurrentUser;
            ViewBag.Opcine = DB.Opcine(user.StrankaID.Value);
            if (id.HasValue) return View(DB.Posmatrac(id.Value, user.StrankaID.Value));
            return View(new UserModel());
        }

        [HttpPost]
        public ActionResult Upsert(UserModel model)
        {
            UserModel user = Constants.CurrentUser;
            if (!ModelState.IsValid)
            {
                ViewBag.Opcine = DB.Opcine(user.StrankaID.Value);
                return View("Index", model);
            }

            if (DB.Posmatrac(model, user.StrankaID.Value))
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Opcine = DB.Opcine(user.StrankaID.Value);
                ModelState.AddModelError("", "Dodavanje glasača nije uspjelo.");
                return View("Index", model);
            }
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            UserModel user = Constants.CurrentUser;
            return Json(new { success = DB.DeleteGlasac(id, user.StrankaID.Value), redirect = Url.Action("Index", "Home") });
        }

        [HttpGet]
        public ActionResult Import()
        {
            return PartialView("_ImportPosmatraci", Session[Session.SessionID] as StrankaViewModel);
        }

        //[HttpPost]
        //public ActionResult Import(long opcinaId, long birackoMjestoId)
        //{
        //    try
        //    {
        //        HttpFileCollectionBase files = Request.Files;
        //        if (files != null && files.Count > 0)
        //        {
        //            var file = files[0];
        //            if (file.ContentLength == 0) return new EmptyResult();
        //            using (TextReader reader = new StreamReader(file.InputStream, System.Text.Encoding.Default))
        //            {
        //                CsvReader csv = new CsvReader(reader);
        //                csv.Configuration.Delimiter = ";";
        //                csv.Configuration.Encoding = System.Text.Encoding.Default;
        //                csv.Configuration.RegisterClassMap<GlasacClassMap>();
        //                var records = csv.GetRecords<GlasacModel>().ToList();
        //                UserModel user = Constants.CurrentUser;
        //                records.ForEach(o =>
        //                {
        //                    o.Ime = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(o.Ime.ToLower());
        //                    o.ImeOca = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(o.ImeOca.ToLower());
        //                    o.Prezime = System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(o.Prezime.ToLower());
        //                    o.OpcinaID = opcinaId;
        //                    o.BirackoMjestoID = birackoMjestoId;
        //                });
        //                DB.ImportGlasaci(records, user.StrankaID.Value);
        //            }
        //        }

        //        return new EmptyResult();
        //    }
        //    catch (Exception ex)
        //    {
        //        return Content(ex.Message);
        //    }
        //}
    }
}

Murtino/Views/Posmatrac/Index.cshtml
@model Murtino.Models.UserModel

@{
    ViewBag.Title = "Posmatrač";
    IEnumerable<Murtino.Models.OpcinaModel> opcine = ViewBag.Opcine as IEnumerable<Murtino.Models.OpcinaModel>;
}

@Html.Partial("_Navbar")

<section class="hero is-fullheight">
    <div class="hero-body">
        <div class="container">
            @using (Html.BeginForm("Upsert", "Posmatrac", null, FormMethod.Post, new { @class = "form form-narrow", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("Id", Model.Id)
                <div class="is-bold is-size-4 has-text-centered" style="margin-bottom: 25px">Podaci o posmatraču</div>
                <div class="field">
                    <label class="label">Korisničko ime</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="Email" name="UserName" value="@Model.UserName">
                    </div>
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "help is-danger" })
                </div>
                <div class="field">
                    <label class="label">Lozinka</label>
                    <div class="control">
                        <input class="input" type="password" placeholder="Minimalno 6 karaktera" name="Password" value="">
                    </div>
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "help is-danger" })
                </div>
                <div class="field">
                    <label class="label">Ime</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="Ime" name="Ime" value="@Model.Ime">
                    </div>
                    @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "help is-danger" })
                </div>
                <div class="field">
                    <label class="label">Prezime</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="Prezime osobe" name="Prezime" value="@Model.Prezime">
                    </div>
                    @Html.ValidationMessageFor(model => model.Prezime, "", new { @class = "help is-danger" })
                </div>
                <div class="field">
                    <label class="label">Broj mobitela</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="06X/XXX-XXX" name="Telefon" value="@Model.Telefon">
                    </div>
                    @Html.ValidationMessageFor(model => Model.Telefon, "", new { @class = "help is-danger" })
                </div>
                <div class="field">
                    <label class="label">Lokacija</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="URL" name="Lokacija" value="@Model.Lokacija">
                    </div>
                    @Html.ValidationMessageFor(model => Model.Lokacija, "", new { @class = "help is-danger" })
                </div>
                <div class="field">
                    <label class="label">Općina</label>
                    <div class="control">
                        <div class="select is-fullwidth">
                            <select name="OpcinaID">
                                @foreach (var opcina in opcine)
                                {
                                    if (opcina.Id == Model.OpcinaID)
                                    {
                                        <option value="@opcina.Id" data-bm="@String.Join(",", opcina.BirackaMjesta.Select(o => String.Format("{0}:{1}", o.Id, o.Naziv)))" selected>@opcina.Naziv</option>
                                    }
                                    else
                                    {
                                        <option value="@opcina.Id" data-bm="@String.Join(",", opcina.BirackaMjesta.Select(o => String.Format("{0}:{1}", o.Id, o.Naziv)))">@opcina.Naziv</option>
                                    }
                                }
                            </select>
                        </div>
                    </div>
                </div>
                <div class="field">
                    <label class="label">Biračko mjesto</label>
                    <div class="control">
                        <div class="select is-fullwidth">
                            @{
                                var opc = opcine.FirstOrDefault(o => o.Id == Model.OpcinaID) ?? opcine.First();
                            }
                            <select name="BirackoMjestoID">
                                @if (opc != null)
                                {
                                    foreach (var bm in opc.BirackaMjesta)
                                    {
                                        if (Model.BirackoMjestoID.HasValue && bm.Id == Model.BirackoMjestoID.Value)
                                        {
                                            <option value="@bm.Id" selected>@bm.Naziv</option>
                                        }
                                        else
                                        {
                                            <option value="@bm.Id">@bm.Naziv</option>
                                        }
                                    }
                                }
                            </select>
                        </div>
                        @Html.ValidationMessageFor(model => model.BirackoMjestoID, "", new { @class = "help is-danger" })
                    </div>
                </div>
                <hr />
                <div class="field is-grouped is-grouped-right">
                    @if (Model.Id != 0)
                    {
                        <p class="control">
                            <button class="button is-danger button-delete" type="button" data-href="@Url.Action("Delete", "Glasac", new { id = Model.Id })" data-title="Ukloniti glasača" data-content="Glasač <b>@Model.Naziv</b> će biti obrisan. Da li ste sigurni?" data-id="@Model.Id">
                                Ukloni
                            </button>
                        </p>
                    }
                    else
                    {
                        <p class="control">
                            <a class="button is-warning" href="@Url.Action("Index", "Home")">
                                Vrati me nazad
                            </a>
                        </p>
                    }
                    <p class="control">
                        <button class="button is-primary" type="submit">
                            Potvrdi
                        </button>
                    </p>
                </div>
                if (Model.Id != 0)
                {
                    <div class="field">
                        <p class="control has-text-centered">
                            <a class="button is-warning is-flex-mobile" href="@Url.Action("Index", "Home")">
                                Vrati me nazad
                            </a>
                        </p>
                    </div>
                }
            }
        </div>
    </div>
</section>