Murtino/Controllers/OpcinaController.cs
using Murtino.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Murtino.Controllers
{
    [Authorize]
    public class OpcinaController : Controller
    {
        public ActionResult Index(long? id)
        {
            UserModel user = Constants.CurrentUser;
            if (id.HasValue) return View(DB.Opcina(id.Value, user.StrankaID.Value));
            return View(new OpcinaModel());
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Upsert(OpcinaModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("Index", model);
            }

            UserModel user = Constants.CurrentUser;
            if (DB.Opcina(model, user.StrankaID.Value)) return RedirectToAction("Index", "Home");
            else
            {
                ModelState.AddModelError("", "Dodavanje stranke nije uspjelo.");
                return View("Index", model);
            }
        }

        [HttpPost]
        public JsonResult Delete(long id)
        {
            UserModel user = Constants.CurrentUser;
            return Json(new { success = DB.DeleteOpcina(id, user.StrankaID.Value), redirect = Url.Action("Index", "Home") });
        }
    }
}

Murtino/Views/Opcina/Index.cshtml
@model Murtino.Models.OpcinaModel

@{
    ViewBag.Title = "Općina";
}

@Html.Partial("_Navbar")

<section class="hero is-fullheight">
    <div class="hero-body">
        <div class="container">
            @using (Html.BeginForm("Upsert", "Opcina", null, FormMethod.Post, new { @class = "form form-narrow", role = "form" }))
            {
                @Html.AntiForgeryToken()
                @Html.Hidden("Id", Model.Id)
                <div class="is-bold is-size-4 has-text-centered" style="margin-bottom: 25px">Podaci o općini</div>
                <div class="field">
                    <label class="label">Naziv općine</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="Naziv općine" name="Naziv" value="@Model.Naziv">
                    </div>
                    @Html.ValidationMessageFor(model => model.Naziv, "", new { @class = "help is-danger" })
                </div>
                <div class="field">
                    <label class="label">Poštanski broj</label>
                    <div class="control">
                        <input class="input" type="text" placeholder="Poštanski broj" name="PostanskiBroj" value="@Model.PostanskiBroj">
                    </div>
                    @Html.ValidationMessageFor(model => model.PostanskiBroj, "", new { @class = "help is-danger" })
                </div>
                <div class="field">
                    <label class="label">Biračka mjesta</label>
                    <div class="control">
                        <div class="field has-addons">
                            <div class="control" style="flex: 1">
                                <input class="input" type="text" placeholder="Naziv biračkog mjesta" id="biracko-mjesto">
                            </div>
                            <div class="control">
                                <a class="button is-success" id="dodaj-opcinu">
                                    Dodaj
                                </a>
                            </div>
                        </div>
                    </div>
                    <div style="margin-top: 10px; ">
                        <table class="table is-bordered is-hoverable is-fullwidth">
                            <thead>
                                <tr>
                                    <th>Naziv</th>
                                    <th style="width: 70px"></th>
                                </tr>
                            </thead>
                            <tbody id="biracka-mjesta">
                                @if (Model.BirackaMjesta.Any())
                                {
                                    int c = 0;
                                    foreach (var mjesto in Model.BirackaMjesta)
                                    {
                                        <tr>

                                            <td>
                                                @mjesto.Naziv
                                            </td>
                                            <td>
                                                <input type="hidden" name="BirackaMjesta[@c].Id" class="BirackoMjestoId" value="@mjesto.Id" />
                                                <input type="hidden" name="BirackaMjesta[@c].Naziv" value="@mjesto.Naziv" />
                                                <a class="bm-remove">Ukloni</a>
                                            </td>
                                        </tr>
                                        c++;
                                    }
                                }
                                else
                                {
                                    <tr id="empty-row">
                                        <td colspan="2" class="has-text-centered is-size-7">
                                            Nema prijavljenih biračkih mjesta.
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <hr />
                <div class="field is-grouped is-grouped-right">
                    @if (Model.Id != 0)
                    {
                        <p class="control">
                            <button class="button is-danger button-delete" type="button" data-href="@Url.Action("Delete", "Opcina", new { id = Model.Id })" data-title="Ukloniti općinu" data-content="Općina <b>@Model.Naziv</b> i pripadajuća biračka mjesta će biti obrisani. Da li ste sigurni?" data-id="@Model.Id">
                                Ukloni
                            </button>
                        </p>
                    }
                    else
                    {
                        <p class="control">
                            <a class="button is-warning" href="@Url.Action("Index", "Home")">
                                Vrati me nazad
                            </a>
                        </p>
                    }
                    <p class="control">
                        <button class="button is-primary" type="submit">
                            Potvrdi
                        </button>
                    </p>
                </div>
                if (Model.Id != 0)
                {
                    <div class="field">
                        <p class="control has-text-centered">
                            <a class="button is-warning is-flex-mobile" href="@Url.Action("Index", "Home")">
                                Vrati me nazad
                            </a>
                        </p>
                    </div>
                }
            }
        </div>
    </div>
</section>